server:
  port: ${PORT:8888}
  shutdown: graceful
spring:
  threads.virtual.enabled: true
  application:
    name: Risa Nail Studio API
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/risa_dev_db}
    username: ${DATABASE_USERNAME:risa_dev_user}
    password: ${DATABASE_PASSWORD:risa_dev_password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
app:
  cors.allowed:
      origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
      methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS,PATCH}
  env:
    is-dev: true
    is-demo: false
  jwt:
    public-key: ${JWT_PUBLIC_KEY}
    private-key: ${JWT_PRIVATE_KEY}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000} # 15 minutos
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7 dias
  security:
    password-salt: ${SECURITY_PASSWORD_SALT:16}
  cookie.domain: ""

scalar:
  theme: kepler
  layout: modern
  dark-mode: true
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    display-operation-id: false
    show-extensions: true
    show-common-extensions: true
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    doc-expansion: none
  show-actuator: false

logging.level.com.smlaurindo.risanailstudio: DEBUG


